name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install surge
      - run: npm install -g surge
      - name: Install dependencies and build code
        run: |
          cd app  # Change directory to the app directory
          npm install  # Install dependencies
          npm run build
      - name: Deploy
        if: success()
        run: surge ./dist https://pdf-in-react-demo.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
